# Generated by Django 5.0 on 2023-12-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
