# Generated by Django 5.0 on 2023-12-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_basket_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='address',
            field=models.CharField(default='Адрес не указан', max_length=100),
        ),
    ]
