# Generated by Django 5.0 on 2023-12-09 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_basket_description_basket_name_alter_basket_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='address',
        ),
    ]
